### PR TITLE
Additional details about V2.0

### PR DESCRIPTION
**Pull request by camillemonchicourt**
To avoid confusion between versions and synchronisation.

### CODE REVIEW

**Comment by camillemonchicourt** [comment]
And to make it clear that Geotrek-rando was totally redesigned in V2.

**Comment by gutard** [comment]
I don't understand this request. Is it about documentation ? Why is it labeled "in progress" ?

**Comment by camillemonchicourt** [comment]
Yes it is about documentation and clarifying releases, dont know why it is In Progress.

**Comment by camillemonchicourt** [comment]
Thanks

**Pull request merged**
