### PR TITLE
Update configuration file name

### PR DESCRIPTION
**Pull request by camillemonchicourt**
The configuration file name changed.

### CODE REVIEW

**Comment by SBats** [comment]
No in fact the default file should never be modified. It's in the custom that you do changes and both are merged in order to create the final one used by the app

**Comment by camillemonchicourt** [comment]
OK so it means that I have to create the file `src/app/config/settings.custom.json` ?
As it doesnt exist after installing Geotrek-rando.

**Comment by SBats** [comment]
You're right. I didn't explicit the fact that you need to create this file. Though it can work if you don't create it. It's optional.

**Comment by camillemonchicourt** [comment]
Yes right, optional if we dont want to change default value. OK thanks.

**Pull request closed without merging**
